/********************************************************************************************
* Class Name: SalutationConstants
* Author: Aditi Bhardwaj (Appirio)
* Date: [2/12/2016]
* Requirement Description: Class containing constant values used for salutation creation process.
* Date Modified                Modified By                  Description of the update

***********************************************************************************************/
public class SalutationConstants {

	// Salutation Use Values
	public static final String INSIDE_CONTACT = 'Inside - Contact';
  public static final String INSIDE_HOUSEHOLD = 'Inside - Household';
  public static final String NAME_CONTACT = 'Name - Contact';
  public static final String OUTSIDE_CONTACT = 'Outside - Contact';
  public static final String OUTSIDE_HOUSEHOLD = 'Outside - Household';
  public static final String OUTSIDE_ORGANIZATION = 'Outside - Organization';
  public static final String PUBLICATION_CONTACT = 'Publication - Contact';
 	public static final String PUBLICATION_ORGANIZATION = 'Publication - Organization';

 	// Salutation type 
  public static final String ORGANIZATION_PREF_MAIL_NAME = 'Organization Pref Mail Name';
  public static final String ORGANIZATION_PUBLICATION_NAME = 'Organization Publication Name';
  public static final String FORMAL_NAME = 'Formal Name';
  public static final String PREF_MAIL_NAME = 'Pref Mail Name';
  public static final String PUBLICATION_NAME = 'Publication Name';
  public static final String HOUSEHOLD_STACKED_PREF_MAIL_NAME = 'Household Stacked Pref Mail Name';
  public static final String HOUSEHOLD_PREF_MAIL_NAME = 'Household Pref Mail Name';
  public static final String HOUSEHOLD_FORMAL = 'Household Formal';
  public static final String HOUSEHOLD_FIRST_NAME = 'Household First Names';
  public static final String HOUSEHOLD_STANDARD_INFORMAL = 'Household Standard Informal';
  public static final String STANDARD_INFORMAL = 'Standard Informal';

  // Added By Aditi B :T-486876/S-370558
  public static final String PREF_MAIL_NAME_LONG = 'Pref Mail Name Long';
  // T-486878/S-370555
  public static final String HOUSEHOLD_STACKED_PREF_MAIL_NAME_LONG = 'Household Stacked Pref Mail Name Long';
  public static final String HOUSEHOLD_PREF_MAIL_NAME_LONG = 'Household Pref Mail Name Long';

  // Added By Aditi B 
  // Task Status and Subject
  public static final String CALL = 'call';
  public static final String COMPLETED  = 'Completed';


  // Added by Aditi B
  // Preference Category 
  public static final String CONSTITUENT_TYPE  = 'Constituent Type';
 
}